//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirstFlightProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFlight
    {
        public int FlightID { get; set; }
        public Nullable<int> DepartureLocation { get; set; }
        public Nullable<int> ArrivalLocation { get; set; }
        public Nullable<System.DateTime> FlightDate { get; set; }
        public Nullable<System.TimeSpan> FlightTime { get; set; }
    }
}
